# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "miniforge3-latest"

python:
  install:
  - method: pip
    path: .

conda:
  environment: docs/environment.yml

submodules:
  include: all