# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: example-docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"

python:
  install:
  - method: pip
    path: .

conda:
  environment: example-docs/environment.yml

submodules:
  include: all