name: Build and upload to PyPi

on:
  push:
    tags:
      - "*"
  release:
    types:
      - published

jobs:
  pypi_push:
    environment: deploy
    if: "github.repository == 'MDAnalysis/mdanalysis-sphinx-theme'"
    name: Build, upload, and test pure Python wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: testpypi_deploy
        uses: MDAnalysis/pypi-deployment@main
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.TESTPYPI_UPLOAD_TOKEN }}
          test_submission: true
          tests: false
          package_name: 'mdanalysis_sphinx_theme'

      - name: pypi_deploy
        uses: MDAnalysis/pypi-deployment@main
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          token: ${{ secrets.PYPI_UPLOAD_TOKEN }}
          tests: false
          package_name: 'mdanalysis_sphinx_theme'

